Repository ome/bioformats, pull requests merged in 2018-09, with the labels that each got.

#3212 Merge v5.9.2 into east
  components/formats-bsd/src/loci/formats/UpgradeChecker.java
  components/formats-bsd/src/loci/formats/in/AVIReader.java
  components/formats-gpl/src/loci/formats/in/DeltavisionReader.java
  components/formats-gpl/src/loci/formats/in/GatanReader.java
  components/formats-gpl/src/loci/formats/in/MRCReader.java
  components/formats-gpl/src/loci/formats/in/ZeissLSMReader.java
Labels: east

#3208 Fix configuration series table retrieval for pyramid detection
  components/test-suite/build.xml
  components/test-suite/src/loci/tests/testng/Configuration.java
  components/test-suite/src/loci/tests/testng/FormatReaderTest.java
Labels: east

#3209 Pyramid reader fixes
  components/formats-gpl/src/loci/formats/in/NDPIReader.java
  components/formats-gpl/src/loci/formats/in/TrestleReader.java
  components/formats-gpl/src/loci/formats/in/VectraReader.java
Labels: east

#3184 Check series count vs OME-XML Image count
  components/test-suite/src/loci/tests/testng/FormatReaderTest.java
Labels: east

#3201 Add test-equivalent target to compare the pixels in two files
  components/test-suite/build.xml
  components/test-suite/src/loci/tests/testng/EquivalentPixelsTest.java
Labels: east

#3221 FormatReaderTest: refactor reader setup methods
  components/test-suite/src/loci/tests/testng/FormatReaderTest.java
Labels: east

#3161 Add .scan extension to MetamorphReader
  components/formats-api/src/loci/formats/readers.txt
  components/formats-gpl/src/loci/formats/in/MetamorphReader.java
Labels: include

#3219 Add new KLB Reader
  components/formats-api/src/loci/formats/readers.txt
  components/formats-gpl/src/loci/formats/in/KLBReader.java
Labels: reader:new
